import { logDebug } from "./logger";
import type { ListTodosOutput, OpenAIWindowBridge, Todo } from "./types";

const delay = (ms = 150) => new Promise((resolve) => setTimeout(resolve, ms));

const generateId = () => {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `dev-${Math.random().toString(36).slice(2, 10)}`;
};

const createSeedTodos = (): Todo[] => [
  {
    id: generateId(),
    subjectId: "dev-subject",
    title: "Sketch UI for todo app",
    notes: "Mirror MCP schema and enrichment states",
    status: "in_progress",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    aiEnrichmentStatus: "complete",
    aiSummary: "Outline created with three follow-up research links.",
    aiLinks: [
      { label: "MCP Spec", url: "https://spec.modelcontextprotocol.io" },
      { label: "Apps SDK", url: "https://platform.openai.com/docs" }
    ],
    aiLastRunAt: new Date().toISOString()
  },
  {
    id: generateId(),
    subjectId: "dev-subject",
    title: "Write enrichment prompt",
    status: "pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    aiEnrichmentStatus: "not_started"
  }
];

export const createDevShim = (): OpenAIWindowBridge => {
  let todos = createSeedTodos();
  const listeners = new Set<(output: ListTodosOutput) => void>();

  const emit = () => {
    const payload: ListTodosOutput = { todos: [...todos] };
    shim.toolOutput = payload;
    listeners.forEach((listener) => listener(payload));
  };

  const findTodo = (id: string) => todos.find((todo) => todo.id === id);

  const shim: OpenAIWindowBridge = {
    toolOutput: { todos: [...todos] },
    onToolOutput: (cb) => {
      listeners.add(cb);
      cb({ todos: [...todos] });
      return () => listeners.delete(cb);
    },
    callTool: async (name, input) => {
      logDebug("dev shim tool call", { name, input });
      await delay();

      switch (name) {
        case "list_todos":
          return { todos: [...todos] } satisfies ListTodosOutput;
        case "create_todo": {
          const title = typeof input?.title === "string" ? input.title.trim() : "";
          if (!title) {
            throw new Error("Title is required");
          }
          const newTodo: Todo = {
            id: generateId(),
            subjectId: "dev-subject",
            title,
            notes: typeof input?.notes === "string" ? input.notes : undefined,
            status: "pending",
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            aiEnrichmentStatus: "not_started"
          };
          todos = [newTodo, ...todos];
          emit();
          return { ok: true };
        }
        case "toggle_todo": {
          const todoId = input?.todoId;
          const target = todoId ? findTodo(todoId) : undefined;
          if (!target) throw new Error("Todo not found");
          target.status = target.status === "done" ? "pending" : "done";
          target.updatedAt = new Date().toISOString();
          emit();
          return { ok: true };
        }
        case "delete_todo": {
          const todoId = input?.todoId;
          todos = todoId ? todos.filter((todo) => todo.id !== todoId) : todos;
          emit();
          return { ok: true };
        }
        case "enrich_todo": {
          const todoId = input?.todoId;
          const target = todoId ? findTodo(todoId) : undefined;
          if (!target) throw new Error("Todo not found");
          target.aiEnrichmentStatus = "running";
          emit();
          void delay(250).then(() => {
            target.aiEnrichmentStatus = "complete";
            target.aiSummary = `Autogenerated summary for ${target.title}`;
            target.aiLinks = [
              { label: "Sample Link", url: "https://example.com" }
            ];
            target.aiLastRunAt = new Date().toISOString();
            emit();
          });
          return { ok: true };
        }
        default:
          throw new Error(`Unsupported tool: ${name}`);
      }
    }
  };

  return shim;
};
